version: "3.8"

services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/google_credentials.json
    networks:
      - app-network

  frontend:
    build:
      context: .
      target: frontend-build
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
